name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to your default branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure the version matches your project

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: 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
          publish_dir: ./storybook-static
